<script setup lang="ts">
useSeoMeta({
  title: 'Privacy — ZaneTheFox.com',
  ogTitle: 'Privacy — ZaneTheFox.com'
});
</script>

<template>
  <div>
    <div class="mx-auto max-w-7xl px-6 lg:px-8 mt-36 md:mt-56">
      <!-- header -->
      <div class="mx-auto max-w-2xl lg:max-w-none">
        <div class="max-w-3xl gap-8 flex flex-col">
          <h1 class="font-d text-4xl font-medium tracking-tight [text-wrap:balance] text-neutral-950 sm:text-5xl">Privacy</h1>

          <p class="text-neutral-600">This website values your privacy and is committed to protecting your data.</p>

          <p class="text-neutral-800 font-semibold">Cookies</p>
          <p class="text-neutral-600">
            This website uses cookies to store your preferences, enhance site functionality, and measure site usage. Some cookies are essential for
            the website to work properly, while others (like those used for analytics) are optional and require your consent. You can manage your
            cookie preferences at any time using the cookie settings link in the footer.
          </p>

          <p class="text-neutral-800 font-semibold">Analytics</p>
          <p class="text-neutral-600">
            Google Analytics, a web analytics service provided by Google Inc. (“Google”), uses cookies to collect information about how visitors use
            the site. This may include data such as pages visited, time spent on the site, and the type of device or browser used. The information
            generated by these cookies is transmitted to and stored by Google on servers in the United States. This data is used exclusively to
            evaluate website performance and improve the user experience.
          </p>

          <p class="text-neutral-600">No personally identifiable information is collected or stored by this website through Google Analytics.</p>

          <p class="text-neutral-800 font-semibold">Security & Performance</p>
          <p class="text-neutral-600">
            The site is served through Cloudflare, a global content delivery network (CDN) and security provider. Cloudflare may collect minimal data
            (like IP address and basic request headers) for the purpose of ensuring site security and optimal delivery speed. This data is not used
            for tracking or marketing.
          </p>

          <p class="text-neutral-800 font-semibold">External Services</p>
          <p class="text-neutral-600">
            Our website uses favicons provided by DuckDuckGo. These favicons are fetched from DuckDuckGo's servers rather than directly from websites.
            DuckDuckGo's service does not track you, create unique cookies, or collect any personal data. This service is part of our commitment to
            maintaining a privacy-first experience on our website. You can learn more about DuckDuckGo
            <NuxtLink
              href="https://duckduckgo.com/duckduckgo-help-pages/privacy/favicons/"
              target="_blank"
              rel="noopener noreferrer"
              class="underline"
              >here</NuxtLink
            >
          </p>
          <p class="text-neutral-600">
            Please note that, while favicons are served by DuckDuckGo, no personal information is collected or shared during this process.
          </p>

          <p class="text-neutral-800 font-semibold">Your Choices</p>
          <p class="text-neutral-600">
            You have the option to customise or withdraw your consent for cookie usage at any time via the cookie settings link available in the
            footer.
          </p>
          <p class="text-neutral-600">
            For any questions or concerns, feel free to <NuxtLink to="/contact" class="underline">get in touch</NuxtLink>.
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped></style>
